version: "3.9"

services:
    db:
      container_name: database
      restart: always
      build:
        context: .
        dockerfile: docker/Dockerfile
      environment:
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - "3306:3306"
      volumes:
        - db:/var/lib/mysql

volumes:
  db:
